# Generated by Django 4.0.7 on 2022-10-27 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='updatedate',
            field=models.DateField(default=datetime.datetime(2022, 10, 27, 10, 48, 7, 623945)),
        ),
    ]
