# Generated by Django 4.1 on 2022-10-10 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('descreption', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('active', 'active'), ('suspended', 'suspended'), ('completed', 'completed'), ('paused', 'paused')], default='active', max_length=50)),
                ('starter_at', models.DateTimeField(null=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
