# Generated by Django 4.0.5 on 2022-11-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_descreption_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='matricule',
            field=models.CharField(default='ffff', max_length=255, unique=True),
        ),
    ]
