# Generated by Django 4.0.5 on 2022-11-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='matricule',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
