# Generated by Django 4.0.5 on 2022-11-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='starter_at',
            field=models.DateField(null=True),
        ),
    ]
