# Generated by Django 4.0.7 on 2022-10-27 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_enddate_alter_task_updatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='updatedate',
            field=models.DateField(default=datetime.datetime(2022, 10, 27, 10, 51, 27, 510212)),
        ),
    ]
